version: "3.8"
services:
  namenode:
    build: ./namenode
    container_name: namenode
    ports:
      - "8000:8000"
    volumes:
      - nn_data:/data
    environment:
      - NN_DB=/data/metadata.db

  datanode:
    build: ./datanode
    environment:
      - NAMENODE_URL=http://namenode:8000
      # DATANODE_URL lo genera Docker con el nombre dinámico del contenedor (como http://datanode1:8001, http://datanode2:8001...)
    volumes:
      - dn_blocks:/data/blocks
    depends_on:
      - namenode
    expose:
      - "8001"   #  Cada datanode escucha internamente en 8001

  client:
    build: ./client
    container_name: grid-client
    environment:
      - NAMENODE_URL=http://namenode:8000
      - BLOCK_SIZE=65536
    depends_on:
      - namenode
    tty: true
    stdin_open: true

volumes:
  nn_data:
  dn_blocks:
